// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD2slmHm5nZZ4f9fJ-7niyS-PfE_f5Q6E',
    appId: '1:953914009597:web:5fc9c2e618b100e0b31b94',
    messagingSenderId: '953914009597',
    projectId: 'my-church-app-project',
    authDomain: 'my-church-app-project.firebaseapp.com',
    storageBucket: 'my-church-app-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAspUr7g7uGs6qwEncpwfhwip01_5do0H4',
    appId: '1:953914009597:android:b61ec08db9561d15b31b94',
    messagingSenderId: '953914009597',
    projectId: 'my-church-app-project',
    storageBucket: 'my-church-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9d_PutePdTJ2jMQE-GeqPkVQZ7bYDP8s',
    appId: '1:953914009597:ios:3ba7e5a8878b126ab31b94',
    messagingSenderId: '953914009597',
    projectId: 'my-church-app-project',
    storageBucket: 'my-church-app-project.firebasestorage.app',
    iosBundleId: 'com.example.churchapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9d_PutePdTJ2jMQE-GeqPkVQZ7bYDP8s',
    appId: '1:953914009597:ios:3ba7e5a8878b126ab31b94',
    messagingSenderId: '953914009597',
    projectId: 'my-church-app-project',
    storageBucket: 'my-church-app-project.firebasestorage.app',
    iosBundleId: 'com.example.churchapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD2slmHm5nZZ4f9fJ-7niyS-PfE_f5Q6E',
    appId: '1:953914009597:web:db8c51086053cdacb31b94',
    messagingSenderId: '953914009597',
    projectId: 'my-church-app-project',
    authDomain: 'my-church-app-project.firebaseapp.com',
    storageBucket: 'my-church-app-project.firebasestorage.app',
  );
}
